### PR TITLE
Fix Orechid

### LINKED ISSUE #8: Vanishing Orechid
## Description (Required)
After some time of use, the orechid throws and error and the block itself vanishes.

## Steps to reproduce the Issue (Required)
Place orechid
use to excess
note when orchid is removed by error

This can take minutes to hours so trying to video this would be pretty futile.  We have several orechids set up with android miners focused on either stone or netherrack blocks being auto-placed with an observer/Block Placer combo.  All goes well until the error is thrown.
orechids

## Expected behavior (Required)
Should basically run until one decides to pause their miner androids or until those droids run out of fuel / the orechid should not vanish or throw an error.

## Server Log / Error Report
[
](https://pastebin.com/385M5dxL)

## Environment (Required)
[03:21:09 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-216 (MC: 1.18.1)
Slimefun DEV - 999 (git e02eedd9)
Metrics-Module #25
Java 17

Installed Addons: (41)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  Networks vDEV - 31 (git 773a911c)
  CrystamaeHistoria vDEV - 58 (git db4a7f0b)
  ExtraTools vDEV - 33 (git 46d26e49)
  FoxyMachines vDEV - 53 (git 22ddcd9c)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  SfChunkInfo vDEV - 4 (git 1859e1a8)
  FNAmplifications vDEV - 46 (git 162f8182)
  SimpleMaterialGenerators vDEV - 1 (git 719e1451)
  DynaTech vDEV - 160 (git e1075a1c)
  ExtraGear vDEV - 13 (git c62047e2)
  InfinityExpansion vDEV - 135 (git 9bc7eba0)
  CMILib v1.1.2.0
  SFCalc vDEV - 36 (git 74973a41)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  ExtraHeads vDEV - 23 (git 0b59a770)
  VillagerUtil vDEV - 1 (git 0a949b19)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  PrivateStorage vDEV - 18 (git 5832db21)
  FlowerPower vDEV - 13 (git 06ad45dc)
  SlimeTinker vDEV - 70 (git 739328ea)
  TranscEndence vDEV - 39 (git cfb66ee5)
  FluffyMachines vDEV - 101 (git 79408746)
  CMI v9.1.3.0
  DyedBackpacks vDEV - 17 (git 8b329e96)
  SoundMuffler vDEV - 22 (git 37411b6c)
  AlchimiaVitae vDEV - 18 (git 9bafe861)
  SlimefunWarfare vDEV - 79 (git 11f4e7e9)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  LiteXpansion vDEV - 155 (git 574d551a)
  SimpleUtils vDEV - 15 (git 4250fd5e)
  ElementManipulation vDEV - 9 (git 4d3ceae6)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)
  SlimyRepair vDEV - 4 (git 790c41cb)

 - Minecraft Version:
 - CS-CoreLib Version: n/a
 - Slimefun Version: dev 999
 - Plugin Version: Dynatech dev 160

### PR DESCRIPTION
**Pull request by Sefiraat**
Fixes #8 

Untested but makes good sense

### CODE REVIEW

File: src/main/java/me/profelements/dynatech/items/tools/Orechid.java [hunk 1]
```diff
@@ -46,8 +46,13 @@ public void tick(Block b) {
...
     
-                if (oreMap.containsKey(relBlock.getType())) {
-                    ItemStack item = oreMap.get(relBlock.getType()).getRandom();
+                if (ORE_MAP.containsKey(relBlock.getType())) {
+                    RandomizedSet<ItemStack> set = ORE_MAP.get(relBlock.getType());
+                    if (set == null) {
+                        continue;
+                    }
+
+                    ItemStack item = ORE_MAP.get(relBlock.getType()).getRandom();
```
Comment (TheBusyBiscuit) [inline src/main/java/me/profelements/dynatech/items/tools/Orechid.java:55]: Here you are performing the same `get` operation THREE times.
Firstly, `.containsKey()` is just a null check on a get operation, then you do a get operation and do a null check yourself, only to do yet another get operation. This can be simplified and optimized a lot here.

```suggestion
                RandomizedSet<ItemStack> set = ORE_MAP.get(relBlock.getType());
                if (set != null) {
                    ItemStack item = set.getRandom();

```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Comment by TheBusyBiscuit** [comment]
> Fixes https://github.com/Slimefun-Addon-Community/DynaTech/pull/9

Also, this is #9. The PR fixes itself 😱

**Review by J3fftw1 — APPROVED** [review]
Lgtm
